# Site settings
title: Heartland API Documentation
email: EntApp_DevPortal@e-hps.com
github_username: hps
url: 'https://hps.github.io'
baseurl: '/Documentation'

# slate settings
slate:
  search: true

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - bin/
